travis:
  secure:
    BINSTAR_TOKEN: UCutc+jCw0bPHqvOIkF1vTtPtd5K5jwkq1qUe/Ur5MevAlZRNT2nzbJxiaJKJaD874bbY0N6tGSdf7tvJVVqmP868DvipXYVSXvtYd9pqFO4iMUo1RSS9REgUMcyjpi4fcpykooa7zh5vKE3qYqKZsOGMMhBkOpVEnZrL7tBBkeJk7Pt6EWlTmyGJ0ezYc71PX/iYBkFNTbu/T9J4zzCMvOOo4KkF1G1t0ZbBWgmsLTgVBoFGhPssyNBiMQasVVdN0NDBeDoDY4UJEzwlpvIhH2600DvTsmYMiLktpDM7BcZPtS6S5zbRXChZoH0BbVUnaRh1N1N8C2YvH5v74Y7O8NBnpX7V8aC2h74XxlAO8hTnPd6Wx1NXRwNvNchNLNy0LD4kYeaTY/xQBO18eSBSPBLDaadDCnzpOo03QS/qzcIJhoQlrCvUDRZc9zIodOYhoM/IhPI8t1ucHzV6UYrt8LAq9s8oY1+Ang52e2LejvLbYjsRlkZmD9VKY+YFv/Z4TZQXXgxc3VweYSVWt+6hcBKwJbb8pZV/SIhXAowFb699AXiTYgFkpUbLsM8ZJKxPhz5szNHOl+9PhMRIfs4mNWH9/Wg4lqOKgaAKR1ZA6nw7SXUxDtYozZAZXUldhCVSJO7+teeE5hY2SlqwmdzRAas2tk2FKIMBkTOgZdYjlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
